# Generated by Django 2.2.16 on 2022-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220302_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(blank=True, verbose_name='Рейтинг произведения'),
        ),
    ]
